version: "3"

services:
  node_qmbe5g5vbejyyaf:
    image: subquerynetwork/subql-node-substrate:v3.6.0
    container_name: node_qmbe5g5vbejyyaf
    restart: always
    cpus: 4
    expose:
      - 3100
    environment:
      DB_USER: postgres
      DB_PASS: gPfpuTq4xRHkRJqLd
      DB_DATABASE: postgres
      DB_HOST: sqidb1.pathrocknetwork.org
      DB_PORT: 5432
    volumes:
      - /home/poi/Qmbe5g5vbEJYYAfpjcwNDzuhjeyaEQPQbxKyKx6PveYnR8:/home/poi/Qmbe5g5vbEJYYAfpjcwNDzuhjeyaEQPQbxKyKx6PveYnR8
    command:
      - -f=ipfs://Qmbe5g5vbEJYYAfpjcwNDzuhjeyaEQPQbxKyKx6PveYnR8
      - -d=https://api.subquery.network/sq/subquery/dictionary-kusama
      - --ipfs=https://sgd.proxy.pathrocknetwork.org:5512/api/v0
      - --network-endpoint=https://sgd.proxy.pathrocknetwork.org:5321
      - --db-schema=schema_qmbe5g5vbejyyaf
      - --port=3100
      - --scale-batch-size=true
      - --store-cache-async=true
      - --store-flush-interval=10
      - --batch-size=100
      - --timeout=1800
      - --workers=2
      - --store-cache-threshold=500
      - --proof-of-index=true
      - --mmr-store-type=file
      - -m=/home/poi/Qmbe5g5vbEJYYAfpjcwNDzuhjeyaEQPQbxKyKx6PveYnR8/.mmr
      - --disable-historical=false
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://node_qmbe5g5vbejyyaf:3100/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 100

  query_qmbe5g5vbejyyaf:
    image: onfinality/subql-query:v2.9.0
    container_name: query_qmbe5g5vbejyyaf
    expose:
      - 3100
    depends_on:
      "node_qmbe5g5vbejyyaf":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: gPfpuTq4xRHkRJqLd
      DB_DATABASE: postgres
      DB_HOST: sqidb1.pathrocknetwork.org
      DB_PORT: 5432
    command:
      - --name=schema_qmbe5g5vbejyyaf
      - --playground
      - --indexer=http://node_qmbe5g5vbejyyaf:3100
      - --port=3100
      - --query-limit=2000

networks:
  default:
    name: indexer_services
